/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.repositories.jooq.tables.pojos;


import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private OffsetDateTime lastCheckTime;
    private Long answersCount;
    private Long commitsCount;

    public Link() {}

    public Link(Link value) {
        this.id = value.id;
        this.url = value.url;
        this.lastCheckTime = value.lastCheckTime;
        this.answersCount = value.answersCount;
        this.commitsCount = value.commitsCount;
    }

    @ConstructorProperties({ "id", "url", "lastCheckTime", "answersCount", "commitsCount" })
    public Link(
        @Nullable Long id,
        @NotNull String url,
        @Nullable OffsetDateTime lastCheckTime,
        @Nullable Long answersCount,
        @Nullable Long commitsCount
    ) {
        this.id = id;
        this.url = url;
        this.lastCheckTime = lastCheckTime;
        this.answersCount = answersCount;
        this.commitsCount = commitsCount;
    }

    /**
     * Getter for <code>LINKS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>LINKS.ID</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>LINKS.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>LINKS.URL</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>LINKS.LAST_CHECK_TIME</code>.
     */
    @Nullable
    public OffsetDateTime getLastCheckTime() {
        return this.lastCheckTime;
    }

    /**
     * Setter for <code>LINKS.LAST_CHECK_TIME</code>.
     */
    public void setLastCheckTime(@Nullable OffsetDateTime lastCheckTime) {
        this.lastCheckTime = lastCheckTime;
    }

    /**
     * Getter for <code>LINKS.ANSWERS_COUNT</code>.
     */
    @Nullable
    public Long getAnswersCount() {
        return this.answersCount;
    }

    /**
     * Setter for <code>LINKS.ANSWERS_COUNT</code>.
     */
    public void setAnswersCount(@Nullable Long answersCount) {
        this.answersCount = answersCount;
    }

    /**
     * Getter for <code>LINKS.COMMITS_COUNT</code>.
     */
    @Nullable
    public Long getCommitsCount() {
        return this.commitsCount;
    }

    /**
     * Setter for <code>LINKS.COMMITS_COUNT</code>.
     */
    public void setCommitsCount(@Nullable Long commitsCount) {
        this.commitsCount = commitsCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Link other = (Link) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.lastCheckTime == null) {
            if (other.lastCheckTime != null)
                return false;
        }
        else if (!this.lastCheckTime.equals(other.lastCheckTime))
            return false;
        if (this.answersCount == null) {
            if (other.answersCount != null)
                return false;
        }
        else if (!this.answersCount.equals(other.answersCount))
            return false;
        if (this.commitsCount == null) {
            if (other.commitsCount != null)
                return false;
        }
        else if (!this.commitsCount.equals(other.commitsCount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.lastCheckTime == null) ? 0 : this.lastCheckTime.hashCode());
        result = prime * result + ((this.answersCount == null) ? 0 : this.answersCount.hashCode());
        result = prime * result + ((this.commitsCount == null) ? 0 : this.commitsCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(lastCheckTime);
        sb.append(", ").append(answersCount);
        sb.append(", ").append(commitsCount);

        sb.append(")");
        return sb.toString();
    }
}
