services:
  postgresql:
    image: postgres:16
    ports:
      - "5050:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: weuizx
      POSTGRES_PASSWORD: weuizx
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }
