/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.repositories.jooq.tables;


import edu.java.scrapper.repositories.jooq.DefaultSchema;
import edu.java.scrapper.repositories.jooq.Keys;
import edu.java.scrapper.repositories.jooq.tables.records.RelationRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Relation extends TableImpl<RelationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CHATSLINKS</code>
     */
    public static final Relation RELATION = new Relation();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<RelationRecord> getRecordType() {
        return RelationRecord.class;
    }

    /**
     * The column <code>CHATSLINKS.ID</code>.
     */
    public final TableField<RelationRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>CHATSLINKS.CHAT_ID</code>.
     */
    public final TableField<RelationRecord, Long> CHAT_ID = createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CHATSLINKS.LINK_ID</code>.
     */
    public final TableField<RelationRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private Relation(Name alias, Table<RelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Relation(Name alias, Table<RelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CHATSLINKS</code> table reference
     */
    public Relation(String alias) {
        this(DSL.name(alias), RELATION);
    }

    /**
     * Create an aliased <code>CHATSLINKS</code> table reference
     */
    public Relation(Name alias) {
        this(alias, RELATION);
    }

    /**
     * Create a <code>CHATSLINKS</code> table reference
     */
    public Relation() {
        this(DSL.name("CHATSLINKS"), null);
    }

    public <O extends Record> Relation(Table<O> child, ForeignKey<O, RelationRecord> key) {
        super(child, key, RELATION);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<RelationRecord, Long> getIdentity() {
        return (Identity<RelationRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<RelationRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_F;
    }

    @Override
    @NotNull
    public List<UniqueKey<RelationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_F023);
    }

    @Override
    @NotNull
    public List<ForeignKey<RelationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_F0, Keys.CONSTRAINT_F02);
    }

    private transient Chat _chats;
    private transient Link _links;

    /**
     * Get the implicit join path to the <code>PUBLIC.CHATS</code> table.
     */
    public Chat chats() {
        if (_chats == null)
            _chats = new Chat(this, Keys.CONSTRAINT_F0);

        return _chats;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Link links() {
        if (_links == null)
            _links = new Link(this, Keys.CONSTRAINT_F02);

        return _links;
    }

    @Override
    @NotNull
    public Relation as(String alias) {
        return new Relation(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Relation as(Name alias) {
        return new Relation(alias, this);
    }

    @Override
    @NotNull
    public Relation as(Table<?> alias) {
        return new Relation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Relation rename(String name) {
        return new Relation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Relation rename(Name name) {
        return new Relation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Relation rename(Table<?> name) {
        return new Relation(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
