/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.repositories.jooq;


import edu.java.scrapper.repositories.jooq.tables.Chat;
import edu.java.scrapper.repositories.jooq.tables.Relation;
import edu.java.scrapper.repositories.jooq.tables.Link;
import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class DefaultSchema extends SchemaImpl {

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>CHATS</code>.
     */
    public final Chat CHATS = Chat.CHAT;

    /**
     * The table <code>CHATSLINKS</code>.
     */
    public final Relation CHATSLINKS = Relation.RELATION;

    /**
     * The table <code>LINKS</code>.
     */
    public final Link LINKS = Link.LINK;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }

    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Chat.CHAT,
            Relation.RELATION,
            Link.LINK
        );
    }
}
