/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.repositories.jooq;


import edu.java.scrapper.repositories.jooq.tables.Chat;
import edu.java.scrapper.repositories.jooq.tables.Relation;
import edu.java.scrapper.repositories.jooq.tables.Link;
import edu.java.scrapper.repositories.jooq.tables.records.ChatRecord;
import edu.java.scrapper.repositories.jooq.tables.records.RelationRecord;
import edu.java.scrapper.repositories.jooq.tables.records.LinkRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_3 =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_3"), new TableField[] {Chat.CHAT.ID}, true);
    public static final UniqueKey<ChatRecord> CONSTRAINT_3D = Internal.createUniqueKey(
        Chat.CHAT,
        DSL.name("CONSTRAINT_3D"),
        new TableField[] {Chat.CHAT.TG_CHAT_ID},
        true
    );
    public static final UniqueKey<RelationRecord> CONSTRAINT_F = Internal.createUniqueKey(
        Relation.RELATION,
        DSL.name("CONSTRAINT_F"),
        new TableField[] {Relation.RELATION.ID},
        true
    );
    public static final UniqueKey<RelationRecord> CONSTRAINT_F023 = Internal.createUniqueKey(
        Relation.RELATION,
        DSL.name("CONSTRAINT_F023"),
        new TableField[] {Relation.RELATION.CHAT_ID, Relation.RELATION.LINK_ID},
        true
    );
    public static final UniqueKey<LinkRecord> CONSTRAINT_4 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_4"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_45 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_45"), new TableField[] {Link.LINK.URL}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<RelationRecord, ChatRecord> CONSTRAINT_F0 =
        Internal.createForeignKey(
            Relation.RELATION,
            DSL.name("CONSTRAINT_F0"),
            new TableField[] {Relation.RELATION.CHAT_ID},
            Keys.CONSTRAINT_3,
            new TableField[] {Chat.CHAT.ID},
            true
        );
    public static final ForeignKey<RelationRecord, LinkRecord> CONSTRAINT_F02 =
        Internal.createForeignKey(
            Relation.RELATION,
            DSL.name("CONSTRAINT_F02"),
            new TableField[] {Relation.RELATION.LINK_ID},
            Keys.CONSTRAINT_4,
            new TableField[] {Link.LINK.ID},
            true
        );
}
