package edu.java.scrapper.repositories.jooq;

import edu.java.scrapper.repositories.jooq.tables.Chat;
import edu.java.scrapper.repositories.jooq.tables.Relation;
import edu.java.scrapper.repositories.jooq.tables.Link;
import javax.annotation.processing.Generated;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>CHATS</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>CHATSLINKS</code>.
     */
    public static final Relation RELATION = Relation.RELATION;

    /**
     * The table <code>LINKS</code>.
     */
    public static final Link LINK = Link.LINK;
}
