CREATE TABLE IF NOT EXISTS chat
(
    id BIGSERIAL PRIMARY KEY,
    tg_chat_id BIGINT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS link
(
    id BIGSERIAL PRIMARY KEY,
    url VARCHAR(255) NOT NULL UNIQUE,
    last_check_time TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    answers_count BIGINT DEFAULT 0 NOT NULL,
    commits_count BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS relation
(
    id BIGSERIAL PRIMARY KEY,
    tg_chat_id BIGINT NOT NULL REFERENCES chat(id) ON DELETE CASCADE,
    link_id BIGINT NOT NULL REFERENCES link(id),
    UNIQUE (tg_chat_id, link_id)
);

